# Generated by Django 2.2.5 on 2019-10-29 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20191029_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='accomodation_check_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 19, 27, 6, 85599, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='service',
            name='accomodation_check_out',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 19, 27, 6, 85628, tzinfo=utc)),
        ),
    ]
