# Generated by Django 2.2.5 on 2019-10-29 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20191029_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='accomodation_check_in',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 29, 19, 27, 47, 778219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='accomodation_check_out',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 29, 19, 27, 47, 778246, tzinfo=utc)),
        ),
    ]
