# Generated by Django 2.2.5 on 2019-10-29 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20191029_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='accomodation_check_in',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 29, 19, 29, 45, 880872, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='accomodation_check_out',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 29, 19, 29, 45, 880899, tzinfo=utc)),
        ),
    ]
