# Generated by Django 2.2.5 on 2019-10-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20191029_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='accomodation_check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='accomodation_check_out',
            field=models.DateTimeField(null=True),
        ),
    ]
