# Generated by Django 2.2.5 on 2019-11-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_auto_20191031_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterField(
            model_name='service',
            name='accomodation_check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='accomodation_check_out',
            field=models.DateField(blank=True),
        ),
    ]
